service: m2m-token-storage
provider:
  name: aws
  runtime: nodejs8.10
  memorySize: 256
  timeout: 15
  environment:
   REDIS_URL: ${file(./config/${self:provider.stage}.json):REDIS_URL}
   DEFAULT_TOKEN_CACHE_TIME: ${file(./config/${self:provider.stage}.json):DEFAULT_TOKEN_CACHE_TIME}

stage: dev   

functions:
 handler:
   handler: lambda.handler
   events:
     - http: ANY /




